// =====================================================================
//  Block Registry — describes every block type the builder knows about.
//  Used by the picker, outline, slash menu, and inspector.
// =====================================================================

import type { BlockType, BlockCategory, BlockPropsMap, Block } from './types'
import { nanoid } from 'nanoid'

export const BLOCK_CATEGORY_LABELS: Record<BlockCategory, string> = {
  text: 'Texte',
  media: 'Médias',
  layout: 'Mise en page',
  marketing: 'Marketing',
  ui: 'UI · shadcn',
  charts: 'Graphiques',
  engagement: 'Engagement',
  navigation: 'Navigation',
  editorial: 'Éditorial',
  docbel: 'DocBel',
  utility: 'Utilitaires',
  decorative: 'Décoratif',
  education: 'Éducation & A11y',
}

export interface BlockRegistryEntry<T extends BlockType = BlockType> {
  type: T
  name: string
  description: string
  category: BlockCategory
  icon: string // lucide icon name
  shortcuts?: string[] // slash command aliases, e.g. ['h1','title']
  defaultProps: BlockPropsMap[T]
  variants?: Array<{
    id: string
    name: string
    description?: string
  }>
  /** Whether this block can have children (columns, section, container) */
  canHaveChildren?: boolean
}

type Registry = { [K in BlockType]: BlockRegistryEntry<K> }

/** Union of every registry entry — preserves the discriminated `type` field. */
export type AnyBlockRegistryEntry = Registry[BlockType]

export const BLOCK_REGISTRY: Registry = {
  // ─────────────── Text & content ───────────────
  heading: {
    type: 'heading',
    name: 'Titre',
    description: 'Titre H1 à H6',
    category: 'text',
    icon: 'heading',
    shortcuts: ['h1', 'h2', 'h3', 'titre', 'heading'],
    defaultProps: { text: 'Titre', level: 2, variant: 'default' },
    variants: [
      { id: 'default', name: 'Standard' },
      { id: 'display', name: 'Display' },
      { id: 'gradient', name: 'Dégradé' },
    ],
  },
  text: {
    type: 'text',
    name: 'Texte',
    description: 'Paragraphe rich-text',
    category: 'text',
    icon: 'type',
    shortcuts: ['p', 'text', 'paragraphe'],
    defaultProps: { html: '<p>Commencez à écrire…</p>', variant: 'default' },
    variants: [
      { id: 'default', name: 'Standard' },
      { id: 'lead', name: 'Lead (large)' },
      { id: 'small', name: 'Petit' },
    ],
  },
  quote: {
    type: 'quote',
    name: 'Citation',
    description: 'Bloc de citation avec auteur',
    category: 'text',
    icon: 'quote',
    shortcuts: ['quote', 'citation'],
    defaultProps: {
      text: 'Une citation inspirante.',
      author: 'Nom',
      role: 'Fonction',
      variant: 'simple',
    },
    variants: [
      { id: 'simple', name: 'Simple' },
      { id: 'pull', name: 'Pull-quote' },
      { id: 'card', name: 'Carte' },
    ],
  },
  divider: {
    type: 'divider',
    name: 'Séparateur',
    description: 'Ligne horizontale',
    category: 'text',
    icon: 'minus',
    shortcuts: ['hr', 'divider', 'separateur', 'ligne'],
    defaultProps: { variant: 'solid', thickness: 1 },
  },
  spacer: {
    type: 'spacer',
    name: 'Espace',
    description: 'Espace vertical',
    category: 'text',
    icon: 'arrow-up-down',
    shortcuts: ['spacer', 'espace'],
    defaultProps: { height: 48 },
  },

  // ─────────────── Media ───────────────
  image: {
    type: 'image',
    name: 'Image',
    description: 'Photo ou illustration',
    category: 'media',
    icon: 'image',
    shortcuts: ['img', 'image', 'photo'],
    defaultProps: {
      url: '',
      alt: '',
      caption: '',
      ratio: 'auto',
      fit: 'cover',
      rounded: 'md',
    },
  },
  video: {
    type: 'video',
    name: 'Vidéo',
    description: 'YouTube, Vimeo ou MP4',
    category: 'media',
    icon: 'video',
    shortcuts: ['video', 'youtube'],
    defaultProps: {
      url: '',
      provider: 'youtube',
      caption: '',
      autoplay: false,
      controls: true,
    },
  },
  gallery: {
    type: 'gallery',
    name: 'Galerie',
    description: 'Grille d’images',
    category: 'media',
    icon: 'images',
    shortcuts: ['gallery', 'galerie'],
    defaultProps: {
      items: [
        { url: '', alt: 'Image 1' },
        { url: '', alt: 'Image 2' },
        { url: '', alt: 'Image 3' },
      ],
      columns: 3,
      variant: 'grid',
      gap: 'md',
    },
  },
  embed: {
    type: 'embed',
    name: 'Embed',
    description: 'iframe ou code HTML',
    category: 'media',
    icon: 'code',
    shortcuts: ['embed', 'iframe'],
    defaultProps: { html: '', height: 400 },
  },

  // ─────────────── Layout ───────────────
  section: {
    type: 'section',
    name: 'Section',
    description: 'Section pleine largeur avec fond',
    category: 'layout',
    icon: 'square',
    shortcuts: ['section'],
    canHaveChildren: true,
    defaultProps: {
      bgType: 'color',
      bgColor: '#F9F9F7',
      fullWidth: true,
    },
  },
  container: {
    type: 'container',
    name: 'Conteneur',
    description: 'Conteneur centré (max-width)',
    category: 'layout',
    icon: 'box',
    shortcuts: ['container', 'conteneur'],
    canHaveChildren: true,
    defaultProps: { width: 'lg' },
  },
  columns: {
    type: 'columns',
    name: 'Colonnes',
    description: 'Grille à 2/3/4 colonnes',
    category: 'layout',
    icon: 'columns-3',
    shortcuts: ['columns', 'colonnes', 'grid'],
    canHaveChildren: true,
    defaultProps: { count: 2, gap: 'md' },
  },

  // ─────────────── Marketing ───────────────
  hero: {
    type: 'hero',
    name: 'Hero',
    description: 'Bannière d’accueil',
    category: 'marketing',
    icon: 'sparkles',
    shortcuts: ['hero', 'banner'],
    defaultProps: {
      title: 'Un titre accrocheur',
      subtitle: 'Sous-titre court',
      description:
        'Description plus longue qui explique en quelques mots ce que vous proposez.',
      ctaText: 'Commencer',
      ctaLink: '#',
      ctaSecondaryText: '',
      ctaSecondaryLink: '',
      image: '',
      bgColor: '#111318',
      variant: 'centered',
    },
    variants: [
      { id: 'centered', name: 'Centré' },
      { id: 'split', name: 'Split (image à droite)' },
      { id: 'minimal', name: 'Minimal' },
      { id: 'fullbleed', name: 'Pleine page' },
    ],
  },
  features: {
    type: 'features',
    name: 'Fonctionnalités',
    description: 'Grille de fonctionnalités',
    category: 'marketing',
    icon: 'grid-2x2',
    shortcuts: ['features', 'avantages'],
    defaultProps: {
      title: 'Pourquoi nous choisir',
      subtitle: 'Quelques arguments clés.',
      items: [
        { icon: '⚡', title: 'Rapide', description: 'Performance optimale.' },
        { icon: '🔒', title: 'Sécurisé', description: 'Données protégées.' },
        { icon: '📱', title: 'Responsive', description: 'Sur tous écrans.' },
      ],
      columns: 3,
      variant: 'cards',
    },
    variants: [
      { id: 'cards', name: 'Cartes' },
      { id: 'icons', name: 'Icônes' },
      { id: 'centered', name: 'Centré' },
    ],
  },
  cta: {
    type: 'cta',
    name: 'Appel à l’action',
    description: 'Bouton ou bannière CTA',
    category: 'marketing',
    icon: 'mouse-pointer-click',
    shortcuts: ['cta', 'bouton', 'button'],
    defaultProps: {
      title: 'Prêt à commencer ?',
      description: 'Rejoignez-nous dès aujourd’hui.',
      text: 'Commencer',
      link: '#',
      secondaryText: '',
      secondaryLink: '',
      variant: 'banner',
      buttonStyle: 'primary',
      buttonSize: 'md',
    },
    variants: [
      { id: 'inline', name: 'Bouton seul' },
      { id: 'banner', name: 'Bannière' },
      { id: 'card', name: 'Carte' },
    ],
  },
  faq: {
    type: 'faq',
    name: 'FAQ',
    description: 'Questions / réponses',
    category: 'marketing',
    icon: 'help-circle',
    shortcuts: ['faq', 'questions'],
    defaultProps: {
      title: 'Questions fréquentes',
      items: [
        { question: 'Question 1 ?', answer: 'Réponse à la première question.' },
        { question: 'Question 2 ?', answer: 'Réponse à la deuxième question.' },
        { question: 'Question 3 ?', answer: 'Réponse à la troisième question.' },
      ],
      variant: 'simple',
    },
    variants: [
      { id: 'simple', name: 'Simple' },
      { id: 'bordered', name: 'Bordée' },
      { id: 'card', name: 'Carte' },
    ],
  },
  testimonial: {
    type: 'testimonial',
    name: 'Témoignage',
    description: 'Avis client',
    category: 'marketing',
    icon: 'message-square-quote',
    shortcuts: ['testimonial', 'temoignage', 'avis'],
    defaultProps: {
      title: 'Ils nous font confiance',
      items: [
        {
          quote: 'Un service exceptionnel, je recommande !',
          author: 'Marie Dupont',
          role: 'CEO, Acme Inc.',
        },
      ],
      variant: 'single',
    },
    variants: [
      { id: 'single', name: 'Simple' },
      { id: 'grid', name: 'Grille' },
      { id: 'carousel', name: 'Carousel' },
    ],
  },
  stats: {
    type: 'stats',
    name: 'Statistiques',
    description: 'Chiffres clés',
    category: 'marketing',
    icon: 'bar-chart-3',
    shortcuts: ['stats', 'chiffres', 'kpi'],
    defaultProps: {
      title: 'Nos chiffres',
      items: [
        { value: '10', suffix: 'k+', label: 'Utilisateurs' },
        { value: '99', suffix: '%', label: 'Satisfaction' },
        { value: '24', suffix: '/7', label: 'Support' },
      ],
      columns: 3,
      variant: 'simple',
    },
    variants: [
      { id: 'simple', name: 'Simple' },
      { id: 'cards', name: 'Cartes' },
      { id: 'centered', name: 'Centré' },
    ],
  },

  // ─────────────── UI · shadcn-style ───────────────
  card: {
    type: 'card',
    name: 'Carte',
    description: 'Carte avec titre, description et CTA',
    category: 'ui',
    icon: 'square',
    shortcuts: ['card', 'carte'],
    defaultProps: {
      title: 'Titre de la carte',
      description: 'Description courte de la carte.',
      body: '',
      image: '',
      ctaText: '',
      ctaLink: '',
      variant: 'default',
    },
    variants: [
      { id: 'default', name: 'Standard' },
      { id: 'bordered', name: 'Bordée' },
      { id: 'elevated', name: 'Avec ombre' },
      { id: 'gradient', name: 'Dégradé' },
    ],
  },
  accordion: {
    type: 'accordion',
    name: 'Accordéon',
    description: 'Sections dépliables',
    category: 'ui',
    icon: 'help-circle',
    shortcuts: ['accordion', 'accordeon'],
    defaultProps: {
      items: [
        { title: 'Section 1', content: 'Contenu de la première section.' },
        { title: 'Section 2', content: 'Contenu de la deuxième section.' },
      ],
      type: 'single',
      variant: 'default',
    },
    variants: [
      { id: 'default', name: 'Standard' },
      { id: 'bordered', name: 'Bordée' },
      { id: 'separated', name: 'Séparée' },
    ],
  },
  tabs: {
    type: 'tabs',
    name: 'Onglets',
    description: 'Contenu organisé en onglets',
    category: 'ui',
    icon: 'columns-3',
    shortcuts: ['tabs', 'onglets'],
    defaultProps: {
      items: [
        { label: 'Onglet 1', content: 'Contenu de l’onglet 1.' },
        { label: 'Onglet 2', content: 'Contenu de l’onglet 2.' },
        { label: 'Onglet 3', content: 'Contenu de l’onglet 3.' },
      ],
      variant: 'default',
    },
    variants: [
      { id: 'default', name: 'Standard' },
      { id: 'pills', name: 'Pilules' },
      { id: 'underline', name: 'Souligné' },
    ],
  },
  alert: {
    type: 'alert',
    name: 'Alerte',
    description: 'Message d’information ou avertissement',
    category: 'ui',
    icon: 'help-circle',
    shortcuts: ['alert', 'info', 'warning', 'avertissement'],
    defaultProps: {
      title: 'Information importante',
      message: 'Voici un message à mettre en évidence.',
      variant: 'info',
      dismissible: false,
      icon: 'info',
    },
    variants: [
      { id: 'info', name: 'Info' },
      { id: 'success', name: 'Succès' },
      { id: 'warning', name: 'Attention' },
      { id: 'destructive', name: 'Erreur' },
    ],
  },
  badges: {
    type: 'badges',
    name: 'Badges',
    description: 'Liste de tags / badges',
    category: 'ui',
    icon: 'square',
    shortcuts: ['badges', 'tags'],
    defaultProps: {
      title: '',
      items: [
        { label: 'Nouveau', variant: 'default' },
        { label: 'Populaire', variant: 'secondary' },
        { label: 'Gratuit', variant: 'outline' },
      ],
      align: 'left',
    },
  },
  progress: {
    type: 'progress',
    name: 'Progression',
    description: 'Barre de progression',
    category: 'ui',
    icon: 'bar-chart-3',
    shortcuts: ['progress', 'progression'],
    defaultProps: {
      label: 'Progression',
      value: 60,
      showValue: true,
      color: '#C8102E',
      variant: 'default',
    },
    variants: [
      { id: 'default', name: 'Linéaire' },
      { id: 'segmented', name: 'Segmentée' },
      { id: 'circular', name: 'Circulaire' },
    ],
  },
  buttonGroup: {
    type: 'buttonGroup',
    name: 'Groupe de boutons',
    description: 'Plusieurs boutons côte à côte',
    category: 'ui',
    icon: 'mouse-pointer-click',
    shortcuts: ['buttons', 'boutons'],
    defaultProps: {
      items: [
        { text: 'Action principale', link: '#', variant: 'primary' },
        { text: 'Action secondaire', link: '#', variant: 'outline' },
      ],
      align: 'left',
      size: 'md',
    },
  },

  // ─────────────── DocBel ───────────────
  document: {
    type: 'document',
    name: 'Document',
    description: 'Fichier téléchargeable lié au file manager',
    category: 'docbel',
    icon: 'file-text',
    shortcuts: ['document', 'doc', 'pdf'],
    defaultProps: {
      title: 'Nom du document',
      description: 'Description ou contexte du document.',
      fileType: 'pdf',
      size: '',
      date: '',
      variant: 'card',
    },
    variants: [
      { id: 'card', name: 'Carte' },
      { id: 'inline', name: 'En ligne' },
      { id: 'list', name: 'Liste compacte' },
    ],
  },
  steps: {
    type: 'steps',
    name: 'Étapes',
    description: 'Procédure pas à pas',
    category: 'docbel',
    icon: 'arrow-up-down',
    shortcuts: ['steps', 'etapes', 'procedure'],
    defaultProps: {
      title: 'Comment ça marche',
      subtitle: '',
      items: [
        { title: 'Étape 1', description: 'Description de la première étape.', icon: '1' },
        { title: 'Étape 2', description: 'Description de la deuxième étape.', icon: '2' },
        { title: 'Étape 3', description: 'Description de la troisième étape.', icon: '3' },
      ],
      orientation: 'horizontal',
      variant: 'numbered',
    },
    variants: [
      { id: 'numbered', name: 'Numérotée' },
      { id: 'icons', name: 'Avec icônes' },
      { id: 'compact', name: 'Compacte' },
    ],
  },
  organisme: {
    type: 'organisme',
    name: 'Organisme',
    description: 'Fiche contact d’un organisme',
    category: 'docbel',
    icon: 'square',
    shortcuts: ['organisme', 'contact'],
    defaultProps: {
      name: 'Nom de l’organisme',
      description: 'Présentation de l’organisme.',
      address: 'Adresse complète',
      phone: '',
      email: '',
      website: '',
      hours: '',
      logo: '',
      variant: 'card',
    },
    variants: [
      { id: 'card', name: 'Carte' },
      { id: 'compact', name: 'Compact' },
      { id: 'detailed', name: 'Détaillé' },
    ],
  },
  glossary: {
    type: 'glossary',
    name: 'Glossaire',
    description: 'Liste de termes et définitions',
    category: 'docbel',
    icon: 'help-circle',
    shortcuts: ['glossary', 'glossaire', 'lexique'],
    defaultProps: {
      title: 'Glossaire',
      items: [
        { term: 'Terme 1', definition: 'Définition du premier terme.' },
        { term: 'Terme 2', definition: 'Définition du deuxième terme.' },
      ],
      variant: 'list',
    },
    variants: [
      { id: 'list', name: 'Liste' },
      { id: 'cards', name: 'Cartes' },
      { id: 'alphabetical', name: 'Alphabétique' },
    ],
  },
  counter: {
    type: 'counter',
    name: 'Compteur animé',
    description: 'Statistiques avec animation au scroll',
    category: 'docbel',
    icon: 'bar-chart-3',
    shortcuts: ['counter', 'compteur'],
    defaultProps: {
      title: '',
      items: [
        { value: 1000, label: 'Utilisateurs', suffix: '+' },
        { value: 99, label: 'Satisfaction', suffix: '%' },
        { value: 24, label: 'Support', suffix: '/7' },
      ],
      columns: 3,
      duration: 2000,
    },
  },
  collection: {
    type: 'collection',
    name: 'Collection',
    description: 'Liste dynamique (news, pages…)',
    category: 'docbel',
    icon: 'grid-2x2',
    shortcuts: ['collection', 'liste', 'news'],
    defaultProps: {
      source: 'news',
      limit: 3,
      layout: 'grid',
      columns: 3,
    },
  },
  form: {
    type: 'form',
    name: 'Formulaire',
    description: 'Champs de saisie + soumission',
    category: 'docbel',
    icon: 'mouse-pointer-click',
    shortcuts: ['form', 'formulaire', 'contact'],
    defaultProps: {
      title: 'Contactez-nous',
      description: 'Remplissez ce formulaire pour nous écrire.',
      fields: [
        { type: 'text', name: 'name', label: 'Nom', required: true },
        { type: 'email', name: 'email', label: 'Email', required: true },
        { type: 'textarea', name: 'message', label: 'Message', required: true },
      ],
      submitText: 'Envoyer',
      successMessage: 'Merci, votre message a bien été envoyé.',
    },
  },

  // ─────────────── Text-extra ───────────────
  codeBlock: {
    type: 'codeBlock',
    name: 'Code',
    description: 'Bloc de code formaté',
    category: 'text',
    icon: 'code',
    shortcuts: ['code', 'pre'],
    defaultProps: {
      code: '// Votre code ici\nconsole.log("Hello world")',
      language: 'javascript',
      filename: '',
      showLineNumbers: true,
    },
  },
  pullQuote: {
    type: 'pullQuote',
    name: 'Pull-quote',
    description: 'Citation typographique large',
    category: 'text',
    icon: 'quote',
    shortcuts: ['pullquote', 'pq'],
    defaultProps: {
      text: 'Une phrase forte qui mérite d\'être mise en valeur.',
      author: '',
      align: 'center',
    },
  },
  dropCap: {
    type: 'dropCap',
    name: 'Lettrine',
    description: 'Première lettre stylisée',
    category: 'text',
    icon: 'type',
    shortcuts: ['dropcap', 'lettrine'],
    defaultProps: {
      html: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget mauris sed lectus dapibus tincidunt.',
      capColor: '#C8102E',
    },
  },
  definitionList: {
    type: 'definitionList',
    name: 'Liste de définitions',
    description: 'Termes et leurs définitions',
    category: 'text',
    icon: 'help-circle',
    shortcuts: ['dl', 'definitions'],
    defaultProps: {
      items: [
        { term: 'Terme 1', definition: 'Définition du premier terme.' },
        { term: 'Terme 2', definition: 'Définition du deuxième terme.' },
      ],
    },
  },
  highlight: {
    type: 'highlight',
    name: 'Surligné',
    description: 'Texte surligné couleur',
    category: 'text',
    icon: 'type',
    shortcuts: ['highlight', 'surligne'],
    defaultProps: { text: 'Texte important', color: 'yellow' },
  },
  prosCons: {
    type: 'prosCons',
    name: 'Pour / Contre',
    description: 'Liste avantages / inconvénients',
    category: 'text',
    icon: 'columns-3',
    shortcuts: ['proscons', 'pros'],
    defaultProps: {
      pros: ['Avantage 1', 'Avantage 2', 'Avantage 3'],
      cons: ['Inconvénient 1', 'Inconvénient 2'],
      prosTitle: 'Avantages',
      consTitle: 'Inconvénients',
    },
  },
  checklist: {
    type: 'checklist',
    name: 'Checklist',
    description: 'Liste avec cases à cocher',
    category: 'text',
    icon: 'check',
    shortcuts: ['checklist', 'todo'],
    defaultProps: {
      title: 'À vérifier',
      items: [
        { text: 'Premier élément', checked: false },
        { text: 'Deuxième élément', checked: false },
        { text: 'Troisième élément', checked: false },
      ],
      interactive: true,
    },
  },

  // ─────────────── Media-extra ───────────────
  audio: {
    type: 'audio',
    name: 'Audio',
    description: 'Lecteur audio',
    category: 'media',
    icon: 'video',
    shortcuts: ['audio', 'podcast', 'mp3'],
    defaultProps: { url: '', title: '', artist: '', caption: '' },
  },
  carousel: {
    type: 'carousel',
    name: 'Carrousel',
    description: 'Slideshow d\'images',
    category: 'media',
    icon: 'images',
    shortcuts: ['carousel', 'slideshow'],
    defaultProps: {
      slides: [
        { image: '', alt: 'Slide 1', caption: '' },
        { image: '', alt: 'Slide 2', caption: '' },
        { image: '', alt: 'Slide 3', caption: '' },
      ],
      autoplay: false,
      interval: 5000,
      showDots: true,
      showArrows: true,
    },
  },
  beforeAfter: {
    type: 'beforeAfter',
    name: 'Avant / Après',
    description: 'Slider de comparaison d\'images',
    category: 'media',
    icon: 'columns-3',
    shortcuts: ['beforeafter', 'compare'],
    defaultProps: {
      beforeUrl: '',
      afterUrl: '',
      beforeLabel: 'Avant',
      afterLabel: 'Après',
      orientation: 'horizontal',
    },
  },
  logoWall: {
    type: 'logoWall',
    name: 'Mur de logos',
    description: 'Bande de logos clients/partenaires',
    category: 'media',
    icon: 'grid-2x2',
    shortcuts: ['logos', 'logowall'],
    defaultProps: {
      title: 'Ils nous font confiance',
      logos: [
        { url: '', alt: 'Logo 1' },
        { url: '', alt: 'Logo 2' },
        { url: '', alt: 'Logo 3' },
        { url: '', alt: 'Logo 4' },
      ],
      variant: 'grid',
      grayscale: true,
    },
  },
  svgIllustration: {
    type: 'svgIllustration',
    name: 'SVG illustration',
    description: 'Code SVG inline',
    category: 'media',
    icon: 'image',
    shortcuts: ['svg'],
    defaultProps: {
      svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="10"/></svg>',
      width: '100px',
      height: '100px',
    },
  },

  // ─────────────── Marketing-extra ───────────────
  pricingTable: {
    type: 'pricingTable',
    name: 'Tableau de tarifs',
    description: 'Plans et prix avec comparaison',
    category: 'marketing',
    icon: 'columns-3',
    shortcuts: ['pricing', 'tarifs', 'plans'],
    defaultProps: {
      title: 'Nos formules',
      subtitle: 'Choisissez ce qui vous correspond.',
      togglePeriod: false,
      plans: [
        {
          name: 'Gratuit',
          price: '0€',
          period: '/mois',
          description: 'Pour découvrir',
          features: ['Fonctionnalité 1', 'Fonctionnalité 2'],
          ctaText: 'Commencer',
          ctaLink: '#',
        },
        {
          name: 'Pro',
          price: '19€',
          period: '/mois',
          description: 'Pour les pros',
          features: ['Tout du Gratuit', 'Fonctionnalité 3', 'Fonctionnalité 4'],
          ctaText: 'Choisir Pro',
          ctaLink: '#',
          highlighted: true,
          badge: 'Populaire',
        },
        {
          name: 'Entreprise',
          price: 'Sur devis',
          features: ['Tout du Pro', 'Support dédié', 'SLA personnalisé'],
          ctaText: 'Nous contacter',
          ctaLink: '#',
        },
      ],
    },
  },
  compareTable: {
    type: 'compareTable',
    name: 'Tableau comparatif',
    description: 'Comparer features vs concurrents',
    category: 'marketing',
    icon: 'columns-3',
    shortcuts: ['compare', 'vs'],
    defaultProps: {
      title: 'Comparaison',
      columns: ['Notre solution', 'Concurrent A', 'Concurrent B'],
      rows: [
        { feature: 'Fonctionnalité 1', values: [true, true, false] },
        { feature: 'Fonctionnalité 2', values: [true, false, true] },
        { feature: 'Fonctionnalité 3', values: [true, false, false] },
        { feature: 'Prix', values: ['Gratuit', '19€', '49€'] },
      ],
      highlightColumn: 0,
    },
  },
  countdown: {
    type: 'countdown',
    name: 'Compte à rebours',
    description: 'Décompte vers une date',
    category: 'marketing',
    icon: 'clock',
    shortcuts: ['countdown', 'timer'],
    defaultProps: {
      targetDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      title: 'Plus que',
      variant: 'large',
      expiredMessage: 'Terminé !',
    },
  },
  notificationBar: {
    type: 'notificationBar',
    name: 'Bandeau d\'annonce',
    description: 'Bandeau en haut de page',
    category: 'marketing',
    icon: 'bell',
    shortcuts: ['banner', 'announce', 'bandeau'],
    defaultProps: {
      message: 'Nouveau : découvrez notre nouvelle fonctionnalité !',
      ctaText: 'En savoir plus',
      ctaLink: '#',
      variant: 'info',
      dismissible: true,
    },
  },
  newsletter: {
    type: 'newsletter',
    name: 'Newsletter inline',
    description: 'Inscription email rapide',
    category: 'marketing',
    icon: 'mail',
    shortcuts: ['newsletter', 'subscribe'],
    defaultProps: {
      title: 'Restez informé',
      description: 'Recevez nos nouveautés une fois par semaine.',
      placeholder: 'votre@email.com',
      buttonText: 'S\'inscrire',
      successMessage: 'Merci, vous êtes inscrit !',
    },
  },
  trustBadges: {
    type: 'trustBadges',
    name: 'Badges de confiance',
    description: 'SSL, paiement, certifs',
    category: 'marketing',
    icon: 'shield',
    shortcuts: ['trust', 'badges'],
    defaultProps: {
      badges: [
        { icon: 'lock', label: 'Paiement sécurisé' },
        { icon: 'shield', label: 'Données protégées' },
        { icon: 'check', label: 'Garantie 30 jours' },
      ],
      align: 'center',
    },
  },
  pressMentions: {
    type: 'pressMentions',
    name: 'Mentions presse',
    description: 'Logos de médias',
    category: 'marketing',
    icon: 'image',
    shortcuts: ['press', 'media', 'asseen'],
    defaultProps: {
      title: 'Vu dans',
      logos: [
        { url: '', alt: 'Le Soir' },
        { url: '', alt: 'RTBF' },
        { url: '', alt: 'L\'Avenir' },
      ],
    },
  },
  starRating: {
    type: 'starRating',
    name: 'Note (étoiles)',
    description: 'Affichage de note 0-5',
    category: 'marketing',
    icon: 'star',
    shortcuts: ['rating', 'stars'],
    defaultProps: { value: 4.5, count: 127, showCount: true, size: 'md' },
  },

  // ─────────────── Charts ───────────────
  barChart: {
    type: 'barChart',
    name: 'Graphique en barres',
    description: 'Bar chart',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['bar', 'chart'],
    defaultProps: {
      title: '',
      data: [
        { label: 'Jan', value: 420 },
        { label: 'Fév', value: 580 },
        { label: 'Mar', value: 650 },
        { label: 'Avr', value: 720 },
      ],
      color: '#C8102E',
      horizontal: false,
      height: 300,
    },
  },
  lineChart: {
    type: 'lineChart',
    name: 'Graphique en lignes',
    description: 'Line chart',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['line'],
    defaultProps: {
      title: '',
      data: [
        { label: 'Jan', value: 420 },
        { label: 'Fév', value: 580 },
        { label: 'Mar', value: 650 },
        { label: 'Avr', value: 720 },
        { label: 'Mai', value: 880 },
      ],
      color: '#C8102E',
      smooth: true,
      height: 300,
    },
  },
  pieChart: {
    type: 'pieChart',
    name: 'Graphique camembert',
    description: 'Pie / Donut chart',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['pie', 'donut'],
    defaultProps: {
      title: '',
      data: [
        { label: 'Mobile', value: 45 },
        { label: 'Desktop', value: 35 },
        { label: 'Tablette', value: 20 },
      ],
      donut: false,
      height: 300,
    },
  },
  kpiCard: {
    type: 'kpiCard',
    name: 'KPI',
    description: 'Indicateur clé avec tendance',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['kpi'],
    defaultProps: {
      label: 'Utilisateurs actifs',
      value: '12 458',
      trendValue: 12.5,
      trendLabel: 'vs mois dernier',
      icon: 'users',
    },
  },
  sparkline: {
    type: 'sparkline',
    name: 'Sparkline',
    description: 'Mini-graphique inline',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['sparkline'],
    defaultProps: {
      data: [10, 14, 12, 18, 22, 28, 35, 32, 40, 45, 50, 58],
      color: '#C8102E',
      label: 'Croissance',
      value: '+23%',
    },
  },
  heatmap: {
    type: 'heatmap',
    name: 'Heatmap calendrier',
    description: 'Activité quotidienne (style GitHub)',
    category: 'charts',
    icon: 'grid-2x2',
    shortcuts: ['heatmap'],
    defaultProps: {
      title: 'Activité',
      data: generateSampleHeatmap(),
      color: '#C8102E',
    },
  },
  chronology: {
    type: 'chronology',
    name: 'Chronologie',
    description: 'Timeline d\'événements',
    category: 'charts',
    icon: 'clock',
    shortcuts: ['timeline', 'chronologie'],
    defaultProps: {
      title: 'Notre histoire',
      events: [
        { date: '2020', title: 'Création', description: 'Lancement du projet.' },
        { date: '2022', title: 'Croissance', description: '10 000 utilisateurs.' },
        { date: '2024', title: 'Expansion', description: 'Nouveaux marchés.' },
      ],
      variant: 'vertical',
    },
  },

  // ─────────────── Engagement ───────────────
  quiz: {
    type: 'quiz',
    name: 'Quiz',
    description: 'Quiz interactif avec résultats',
    category: 'engagement',
    icon: 'help-circle',
    shortcuts: ['quiz'],
    defaultProps: {
      title: 'Testez vos connaissances',
      questions: [
        {
          question: 'Quelle est la capitale de la Belgique ?',
          options: ['Anvers', 'Bruxelles', 'Liège', 'Gand'],
          correct: 1,
          explanation: 'Bruxelles est la capitale et siège des institutions européennes.',
        },
      ],
    },
  },
  poll: {
    type: 'poll',
    name: 'Sondage',
    description: 'Vote en direct',
    category: 'engagement',
    icon: 'bar-chart-3',
    shortcuts: ['poll', 'vote', 'sondage'],
    defaultProps: {
      question: 'Quelle est votre opinion ?',
      options: [
        { label: 'Très favorable', votes: 0 },
        { label: 'Favorable', votes: 0 },
        { label: 'Mitigé', votes: 0 },
        { label: 'Défavorable', votes: 0 },
      ],
    },
  },
  calculator: {
    type: 'calculator',
    name: 'Calculatrice',
    description: 'Calcul personnalisé',
    category: 'engagement',
    icon: 'bar-chart-3',
    shortcuts: ['calculator', 'calcul'],
    defaultProps: {
      title: 'Calculez votre montant',
      description: '',
      fields: [
        { name: 'salary', label: 'Salaire mensuel brut', type: 'number', defaultValue: 2500, unit: '€' },
      ],
      formula: 'salary * 0.65',
      resultLabel: 'Net estimé',
      resultUnit: '€',
      resultPrecision: 2,
    },
  },
  reactions: {
    type: 'reactions',
    name: 'Réactions',
    description: 'Boutons emoji like/love',
    category: 'engagement',
    icon: 'heart',
    shortcuts: ['reactions'],
    defaultProps: {
      reactions: [
        { emoji: '👍', label: 'J\'aime', count: 0 },
        { emoji: '❤️', label: 'J\'adore', count: 0 },
        { emoji: '🎉', label: 'Bravo', count: 0 },
        { emoji: '🤔', label: 'Réflexion', count: 0 },
      ],
    },
  },
  shareButtons: {
    type: 'shareButtons',
    name: 'Partager',
    description: 'Boutons de partage social',
    category: 'engagement',
    icon: 'arrow-up-right',
    shortcuts: ['share', 'partager'],
    defaultProps: {
      platforms: ['twitter', 'linkedin', 'facebook', 'email', 'copy'],
      align: 'left',
      size: 'md',
    },
  },

  // ─────────────── Time / Nav ───────────────
  openingHours: {
    type: 'openingHours',
    name: 'Horaires',
    description: 'Heures d\'ouverture',
    category: 'navigation',
    icon: 'clock',
    shortcuts: ['hours', 'horaires'],
    defaultProps: {
      title: 'Horaires d\'ouverture',
      schedule: [
        { day: 'mon', open: '09:00', close: '17:00' },
        { day: 'tue', open: '09:00', close: '17:00' },
        { day: 'wed', open: '09:00', close: '17:00' },
        { day: 'thu', open: '09:00', close: '17:00' },
        { day: 'fri', open: '09:00', close: '17:00' },
        { day: 'sat', closed: true },
        { day: 'sun', closed: true },
      ],
      showCurrentStatus: true,
    },
  },
  lastUpdated: {
    type: 'lastUpdated',
    name: 'Dernière mise à jour',
    description: 'Tampon date de mise à jour',
    category: 'navigation',
    icon: 'clock',
    shortcuts: ['updated', 'misajour'],
    defaultProps: { format: 'long', prefix: 'Mis à jour' },
  },
  tableOfContents: {
    type: 'tableOfContents',
    name: 'Sommaire',
    description: 'Table des matières auto',
    category: 'navigation',
    icon: 'help-circle',
    shortcuts: ['toc', 'sommaire'],
    defaultProps: { title: 'Sommaire', sticky: false, maxLevel: 3 },
  },
  anchorMenu: {
    type: 'anchorMenu',
    name: 'Menu d\'ancres',
    description: 'Navigation par section',
    category: 'navigation',
    icon: 'arrow-right',
    shortcuts: ['anchor', 'menu'],
    defaultProps: {
      items: [
        { label: 'Section 1', anchor: 'section-1' },
        { label: 'Section 2', anchor: 'section-2' },
      ],
      sticky: true,
    },
  },
  backToTop: {
    type: 'backToTop',
    name: 'Retour en haut',
    description: 'Bouton remontée flottant',
    category: 'navigation',
    icon: 'arrow-up-right',
    shortcuts: ['top', 'totop'],
    defaultProps: { threshold: 400 },
  },
  readingProgress: {
    type: 'readingProgress',
    name: 'Barre de lecture',
    description: 'Progression de lecture sticky',
    category: 'navigation',
    icon: 'bar-chart-3',
    shortcuts: ['progress', 'reading'],
    defaultProps: { color: '#C8102E', height: 3 },
  },

  // ─────────────── Editorial ───────────────
  articleHeader: {
    type: 'articleHeader',
    name: 'En-tête article',
    description: 'Titre + auteur + date + temps de lecture',
    category: 'editorial',
    icon: 'file-text',
    shortcuts: ['articleheader'],
    defaultProps: {
      category: 'Actualité',
      title: 'Titre de l\'article',
      excerpt: 'Sous-titre ou résumé.',
      authorName: 'Auteur',
      authorAvatar: '',
      date: new Date().toISOString(),
      readingTime: 5,
      image: '',
    },
  },
  authorBio: {
    type: 'authorBio',
    name: 'Bio auteur',
    description: 'Carte de présentation auteur',
    category: 'editorial',
    icon: 'user',
    shortcuts: ['author', 'bio'],
    defaultProps: {
      name: 'Nom de l\'auteur',
      bio: 'Une courte biographie.',
      avatar: '',
      twitter: '',
      linkedin: '',
      website: '',
    },
  },
  sponsoredDisclosure: {
    type: 'sponsoredDisclosure',
    name: 'Mention sponsorisée',
    description: 'Disclosure contenu sponsorisé',
    category: 'editorial',
    icon: 'shield',
    shortcuts: ['sponsored'],
    defaultProps: { sponsor: '' },
  },

  // ─────────────── DocBel-extra ───────────────
  belgianDateHelper: {
    type: 'belgianDateHelper',
    name: 'Calculateur de date BE',
    description: 'Calcul délais avec jours fériés belges',
    category: 'docbel',
    icon: 'calendar',
    shortcuts: ['dateBE', 'delai'],
    defaultProps: {
      startDate: new Date().toISOString().slice(0, 10),
      daysToAdd: 30,
      countWeekendsAndHolidays: 'businessOnly',
      label: 'Date de fin estimée',
    },
  },
  tarifsTable: {
    type: 'tarifsTable',
    name: 'Tarifs / Allocations',
    description: 'Table de montants par situation',
    category: 'docbel',
    icon: 'bar-chart-3',
    shortcuts: ['tarifs', 'allocations', 'montants'],
    defaultProps: {
      title: 'Montants en vigueur',
      subtitle: '',
      rows: [
        { situation: 'Cohabitant', montant: '985,00 €', periode: '/ mois' },
        { situation: 'Isolé', montant: '1 300,00 €', periode: '/ mois' },
        { situation: 'Avec famille à charge', montant: '1 715,00 €', periode: '/ mois' },
      ],
      source: 'SPF Sécurité sociale',
    },
  },
  eligibilityTest: {
    type: 'eligibilityTest',
    name: 'Test d\'éligibilité',
    description: 'Mini-quiz oui/non avec résultat',
    category: 'docbel',
    icon: 'check',
    shortcuts: ['eligibility', 'eligible'],
    defaultProps: {
      title: 'Êtes-vous éligible ?',
      introText: 'Répondez à ces questions pour le savoir.',
      questions: [
        { question: 'Avez-vous plus de 18 ans ?', type: 'yesno' },
        { question: 'Résidez-vous en Belgique ?', type: 'yesno' },
        { question: 'Avez-vous travaillé au moins 312 jours ?', type: 'yesno' },
      ],
      rules: {
        allYes: true,
        resultIfPass: 'Vous êtes potentiellement éligible. Contactez l\'organisme pour confirmer.',
        resultIfFail: 'Vous n\'êtes peut-être pas éligible — consultez un conseiller.',
      },
    },
  },
  lawCitation: {
    type: 'lawCitation',
    name: 'Citation de loi',
    description: 'Article de loi formaté',
    category: 'docbel',
    icon: 'file-text',
    shortcuts: ['law', 'loi', 'article'],
    defaultProps: {
      reference: 'Art. 23 — LOI du 26 mai 2002',
      text: 'Toute personne a droit à l\'intégration sociale. Ce droit peut, dans les conditions fixées par la présente loi, prendre la forme d\'un emploi et/ou d\'un revenu d\'intégration.',
      source: 'Moniteur belge',
      link: '',
    },
  },
  casePractice: {
    type: 'casePractice',
    name: 'Cas pratique',
    description: 'Situation concrète + démarche',
    category: 'docbel',
    icon: 'file-text',
    shortcuts: ['cas', 'casepractice'],
    defaultProps: {
      title: 'Cas pratique',
      situation: 'Marie, 35 ans, vient de perdre son emploi après 8 ans dans la même entreprise.',
      steps: [
        'Marie se rend au CPAS de sa commune.',
        'Elle introduit une demande d\'allocations de chômage.',
        'Le CPAS examine sa situation sous 30 jours.',
      ],
      outcome: 'Marie reçoit ses premières allocations le mois suivant.',
    },
  },
  requiredDocs: {
    type: 'requiredDocs',
    name: 'Documents requis',
    description: 'Checklist des pièces à fournir',
    category: 'docbel',
    icon: 'file-text',
    shortcuts: ['docs', 'documents'],
    defaultProps: {
      title: 'Pièces à fournir',
      items: [
        { name: 'Carte d\'identité', required: true, description: 'Recto-verso' },
        { name: 'Justificatif de domicile', required: true },
        { name: 'Composition de ménage', required: true },
        { name: 'Preuve de revenus', required: false, description: 'Si applicable' },
      ],
    },
  },
  legalDelay: {
    type: 'legalDelay',
    name: 'Délai légal',
    description: 'Affichage gros chiffre + contexte',
    category: 'docbel',
    icon: 'clock',
    shortcuts: ['delai', 'delay'],
    defaultProps: {
      delay: '30 jours',
      context: 'pour introduire un recours',
      variant: 'large',
    },
  },

  // ─────────────── Story ───────────────
  marquee: {
    type: 'marquee',
    name: 'Texte défilant',
    description: 'Bandeau qui défile en boucle',
    category: 'utility',
    icon: 'arrow-right',
    shortcuts: ['marquee', 'defile'],
    defaultProps: {
      text: '✨ Annonce importante · Nouveauté · Ne manquez pas ça · ',
      speed: 'normal',
      reverse: false,
      color: '#C8102E',
    },
  },
  tiltCard: {
    type: 'tiltCard',
    name: 'Carte 3D',
    description: 'Carte avec effet 3D au hover',
    category: 'ui',
    icon: 'square',
    shortcuts: ['tilt'],
    defaultProps: {
      title: 'Carte interactive',
      description: 'Survolez-moi pour voir l\'effet.',
      image: '',
      link: '',
    },
  },
  imageHotspots: {
    type: 'imageHotspots',
    name: 'Image avec points',
    description: 'Image cliquable avec hotspots',
    category: 'media',
    icon: 'image',
    shortcuts: ['hotspots'],
    defaultProps: {
      image: '',
      alt: '',
      hotspots: [
        { x: 25, y: 30, title: 'Point 1', description: 'Description du point 1.' },
        { x: 60, y: 70, title: 'Point 2', description: 'Description du point 2.' },
      ],
    },
  },

  // ─────────────── Utility ───────────────
  htmlRaw: {
    type: 'htmlRaw',
    name: 'HTML brut',
    description: '⚠️ Code HTML injecté tel quel',
    category: 'utility',
    icon: 'code',
    shortcuts: ['html', 'raw'],
    defaultProps: { html: '<div>Votre HTML ici</div>' },
  },
  customCss: {
    type: 'customCss',
    name: 'CSS custom',
    description: 'CSS appliqué à la page',
    category: 'utility',
    icon: 'code',
    shortcuts: ['css'],
    defaultProps: { css: '/* Votre CSS ici */' },
  },
  gdprNotice: {
    type: 'gdprNotice',
    name: 'Bannière GDPR',
    description: 'Bandeau cookies RGPD',
    category: 'utility',
    icon: 'shield',
    shortcuts: ['gdpr', 'rgpd', 'cookies'],
    defaultProps: {
      message: 'Nous utilisons des cookies pour améliorer votre expérience. En continuant, vous acceptez notre politique.',
      acceptText: 'Accepter',
      declineText: 'Refuser',
      linkText: 'En savoir plus',
      link: '/mentions-legales',
    },
  },
  mapEmbed: {
    type: 'mapEmbed',
    name: 'Carte',
    description: 'Carte OpenStreetMap embeddée',
    category: 'media',
    icon: 'map-pin',
    shortcuts: ['map', 'carte'],
    defaultProps: {
      query: 'Bruxelles, Belgique',
      zoom: 14,
      height: 400,
      caption: '',
    },
  },

  // ═════════════════════ Layout-flex ═════════════════════
  bentoGrid: {
    type: 'bentoGrid',
    name: 'Bento grid',
    description: 'Grille asymétrique style Apple',
    category: 'layout',
    icon: 'grid-2x2',
    shortcuts: ['bento', 'grid'],
    defaultProps: {
      title: '',
      cols: 4,
      cells: [
        { span: { col: 2, row: 2 }, title: 'Cellule large', description: 'Span 2x2', variant: 'highlighted' },
        { span: { col: 2 }, title: 'Cellule horizontale', description: 'Span 2x1' },
        { span: {}, title: 'Petite', description: '1x1' },
        { span: {}, title: 'Petite', description: '1x1' },
      ],
    },
    variants: [
      { id: 'default', name: 'Standard' },
      { id: 'compact', name: 'Compact' },
    ],
  },
  splitSection: {
    type: 'splitSection',
    name: 'Section split',
    description: 'Deux colonnes avec ratio configurable',
    category: 'layout',
    icon: 'columns-3',
    shortcuts: ['split'],
    canHaveChildren: true,
    defaultProps: { ratio: '50-50', reverseOnMobile: false },
  },
  stickyDuo: {
    type: 'stickyDuo',
    name: 'Sticky duo',
    description: 'Une colonne fixe pendant le scroll',
    category: 'layout',
    icon: 'columns-3',
    shortcuts: ['sticky', 'duo'],
    canHaveChildren: true,
    defaultProps: { stickySide: 'left', topOffset: 80 },
  },
  flexContainer: {
    type: 'flexContainer',
    name: 'Conteneur flex',
    description: 'Container flexbox configurable',
    category: 'layout',
    icon: 'box',
    shortcuts: ['flex'],
    canHaveChildren: true,
    defaultProps: {
      direction: 'row',
      gap: 'md',
      align: 'start',
      justify: 'start',
      wrap: true,
    },
  },
  magazineColumns: {
    type: 'magazineColumns',
    name: 'Colonnes magazine',
    description: 'Texte sur plusieurs colonnes journal',
    category: 'layout',
    icon: 'columns-3',
    shortcuts: ['columns', 'magazine'],
    defaultProps: {
      html: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum euismod, sapien at malesuada egestas, justo ipsum vehicula nisi, in pharetra purus mi non massa.</p><p>Aenean fermentum, eros eu pellentesque eleifend, lectus mi euismod orci.</p>',
      columns: 2,
      gap: 'md',
    },
  },

  // ═════════════════════ Charts-extra ═════════════════════
  radarChart: {
    type: 'radarChart',
    name: 'Radar chart',
    description: 'Graphique radar / spider',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['radar', 'spider'],
    defaultProps: {
      title: '',
      data: [
        { label: 'Performance', value: 80 },
        { label: 'Sécurité', value: 90 },
        { label: 'Design', value: 75 },
        { label: 'Support', value: 85 },
        { label: 'Prix', value: 70 },
      ],
      color: '#C8102E',
      height: 300,
    },
  },
  funnelChart: {
    type: 'funnelChart',
    name: 'Funnel',
    description: 'Entonnoir de conversion',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['funnel', 'entonnoir'],
    defaultProps: {
      title: '',
      stages: [
        { label: 'Visiteurs', value: 10000 },
        { label: 'Inscriptions', value: 1500 },
        { label: 'Activations', value: 850 },
        { label: 'Clients', value: 250 },
      ],
      color: '#C8102E',
    },
  },
  gauge: {
    type: 'gauge',
    name: 'Jauge',
    description: 'Indicateur en arc de cercle',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['gauge', 'jauge'],
    defaultProps: { label: 'Score', value: 75, color: '#C8102E', showValue: true },
  },
  stackedBar: {
    type: 'stackedBar',
    name: 'Barres empilées',
    description: 'Stacked bar chart',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['stacked'],
    defaultProps: {
      title: '',
      series: ['Q1', 'Q2', 'Q3', 'Q4'],
      data: [
        { label: 'Bxl', values: { Q1: 120, Q2: 150, Q3: 180, Q4: 200 } },
        { label: 'Liège', values: { Q1: 80, Q2: 95, Q3: 110, Q4: 130 } },
        { label: 'Gand', values: { Q1: 95, Q2: 105, Q3: 120, Q4: 140 } },
      ],
      height: 300,
    },
  },
  multiLine: {
    type: 'multiLine',
    name: 'Multi-line',
    description: 'Plusieurs courbes',
    category: 'charts',
    icon: 'bar-chart-3',
    shortcuts: ['multiline'],
    defaultProps: {
      title: '',
      series: ['2023', '2024'],
      data: [
        { label: 'Jan', values: { '2023': 420, '2024': 580 } },
        { label: 'Fév', values: { '2023': 480, '2024': 620 } },
        { label: 'Mar', values: { '2023': 550, '2024': 720 } },
        { label: 'Avr', values: { '2023': 600, '2024': 800 } },
      ],
      height: 300,
    },
  },

  // ═════════════════════ Text-rich ═════════════════════
  spoiler: {
    type: 'spoiler',
    name: 'Spoiler',
    description: 'Contenu masqué cliquable',
    category: 'text',
    icon: 'eye',
    shortcuts: ['spoiler', 'reveal'],
    defaultProps: {
      summary: 'Cliquez pour révéler la réponse',
      content: 'Réponse cachée. Vous pouvez écrire plusieurs lignes ici.',
      variant: 'default',
    },
  },
  aside: {
    type: 'aside',
    name: 'Encart',
    description: 'Note latérale (info/tip/warning)',
    category: 'text',
    icon: 'help-circle',
    shortcuts: ['aside', 'note', 'tip'],
    defaultProps: {
      title: 'Bon à savoir',
      content: 'Information complémentaire utile au lecteur.',
      variant: 'info',
    },
    variants: [
      { id: 'info', name: 'Info' },
      { id: 'tip', name: 'Astuce' },
      { id: 'warning', name: 'Attention' },
      { id: 'note', name: 'Note' },
    ],
  },
  editorNote: {
    type: 'editorNote',
    name: 'Note de l\'éditeur',
    description: 'Encadré "Note de la rédaction"',
    category: 'text',
    icon: 'file-text',
    shortcuts: ['editor', 'note'],
    defaultProps: {
      content: 'Mise à jour : précisions ajoutées suite aux retours de nos lecteurs.',
      signedBy: 'La rédaction',
    },
  },
  dialogBlock: {
    type: 'dialogBlock',
    name: 'Conversation',
    description: 'Dialogue style chat',
    category: 'text',
    icon: 'message-circle',
    shortcuts: ['dialog', 'chat'],
    defaultProps: {
      title: '',
      turns: [
        { speaker: 'Marie', message: 'Comment introduire ma demande ?', side: 'left' },
        { speaker: 'Conseiller', message: 'Vous pouvez le faire en ligne ou en personne au CPAS.', side: 'right' },
        { speaker: 'Marie', message: 'Quels documents apporter ?', side: 'left' },
      ],
    },
  },
  diffViewer: {
    type: 'diffViewer',
    name: 'Diff',
    description: 'Comparaison avant / après',
    category: 'text',
    icon: 'columns-3',
    shortcuts: ['diff'],
    defaultProps: {
      before: 'Ancienne version\nLigne 2 inchangée',
      after: 'Nouvelle version\nLigne 2 inchangée',
      language: 'text',
      filename: '',
    },
  },
  mathLatex: {
    type: 'mathLatex',
    name: 'Formule LaTeX',
    description: 'Équation mathématique (rendu basique)',
    category: 'text',
    icon: 'help-circle',
    shortcuts: ['math', 'latex'],
    defaultProps: { formula: 'a² + b² = c²', display: 'block' },
  },

  // ═════════════════════ Engagement-extra ═════════════════════
  feedbackBar: {
    type: 'feedbackBar',
    name: 'Cette page vous a-t-elle aidé ?',
    description: 'Feedback rapide 👍/👎',
    category: 'engagement',
    icon: 'heart',
    shortcuts: ['feedback', 'helpful'],
    defaultProps: {
      question: 'Cette page vous a-t-elle été utile ?',
      thanksMessage: 'Merci pour votre retour !',
    },
  },
  suggestionBox: {
    type: 'suggestionBox',
    name: 'Boîte à idées',
    description: 'Soumettre une suggestion',
    category: 'engagement',
    icon: 'mail',
    shortcuts: ['suggestion', 'idee'],
    defaultProps: {
      title: 'Une idée d\'amélioration ?',
      placeholder: 'Votre suggestion…',
    },
  },
  multiStepForm: {
    type: 'multiStepForm',
    name: 'Formulaire multi-étapes',
    description: 'Formulaire en plusieurs écrans',
    category: 'engagement',
    icon: 'mouse-pointer-click',
    shortcuts: ['multistep', 'wizard'],
    defaultProps: {
      title: 'Demande en plusieurs étapes',
      steps: [
        {
          title: 'Vos coordonnées',
          fields: [
            { type: 'text', name: 'name', label: 'Nom', required: true },
            { type: 'email', name: 'email', label: 'Email', required: true },
          ],
        },
        {
          title: 'Votre situation',
          fields: [
            { type: 'select', name: 'situation', label: 'Statut', options: ['Isolé', 'Cohabitant', 'Famille à charge'] },
          ],
        },
        {
          title: 'Détails',
          fields: [
            { type: 'textarea', name: 'message', label: 'Décrivez votre demande', required: true },
          ],
        },
      ],
      submitText: 'Envoyer la demande',
      successMessage: 'Demande envoyée, merci !',
    },
  },
  donation: {
    type: 'donation',
    name: 'Don / Soutien',
    description: 'Bouton de soutien avec presets',
    category: 'engagement',
    icon: 'heart',
    shortcuts: ['donation', 'don'],
    defaultProps: {
      title: 'Soutenir Docbel',
      description: 'Votre soutien aide à maintenir ce service gratuit.',
      presets: [5, 10, 20, 50],
      buttonText: 'Faire un don',
      link: '#',
    },
  },

  // ═════════════════════ DocBel calculators ═════════════════════
  salaireNetBE: {
    type: 'salaireNetBE',
    name: 'Salaire brut → net BE',
    description: 'Estime le salaire net belge',
    category: 'docbel',
    icon: 'bar-chart-3',
    shortcuts: ['salaire', 'net'],
    defaultProps: { title: 'Salaire net estimé', defaultBrut: 3000, status: 'isolé' },
  },
  preavisCCT109: {
    type: 'preavisCCT109',
    name: 'Préavis CCT 109',
    description: 'Calcul du préavis selon ancienneté (Belgique)',
    category: 'docbel',
    icon: 'clock',
    shortcuts: ['preavis', 'cct'],
    defaultProps: { title: 'Calculateur de préavis', defaultMonths: 24 },
  },
  allocationsFamiliales: {
    type: 'allocationsFamiliales',
    name: 'Allocations familiales',
    description: 'Estimation par région',
    category: 'docbel',
    icon: 'heart',
    shortcuts: ['allocations', 'famille'],
    defaultProps: { title: 'Allocations familiales', region: 'wallonie' },
  },
  postalToCommune: {
    type: 'postalToCommune',
    name: 'Code postal → commune',
    description: 'Trouve la commune belge',
    category: 'docbel',
    icon: 'map-pin',
    shortcuts: ['postal', 'cp', 'commune'],
    defaultProps: { title: 'Trouver ma commune', defaultCode: '1000' },
  },
  bceValidator: {
    type: 'bceValidator',
    name: 'Validateur BCE/KBO',
    description: 'Vérifie un n° d\'entreprise belge',
    category: 'docbel',
    icon: 'check',
    shortcuts: ['bce', 'kbo', 'tva'],
    defaultProps: { title: 'Vérifier un numéro BCE/KBO' },
  },

  // ═════════════════════ Decorative ═════════════════════
  gradientMesh: {
    type: 'gradientMesh',
    name: 'Gradient mesh',
    description: 'Fond dégradé multi-couleurs',
    category: 'decorative',
    icon: 'sparkles',
    shortcuts: ['gradient', 'mesh'],
    defaultProps: {
      colors: ['#C8102E', '#3B82F6', '#10B981', '#F59E0B'],
      height: 300,
      animated: true,
    },
  },
  sectionDivider: {
    type: 'sectionDivider',
    name: 'Séparateur SVG',
    description: 'Vague, courbe, montagne…',
    category: 'decorative',
    icon: 'minus',
    shortcuts: ['divider', 'wave'],
    defaultProps: {
      variant: 'wave',
      color: '#F9F9F7',
      height: 80,
      flip: false,
    },
    variants: [
      { id: 'wave', name: 'Vague' },
      { id: 'curve', name: 'Courbe' },
      { id: 'angle', name: 'Angle' },
      { id: 'mountains', name: 'Montagnes' },
      { id: 'zigzag', name: 'Zigzag' },
    ],
  },
  glassCard: {
    type: 'glassCard',
    name: 'Carte verre',
    description: 'Glassmorphism avec effet flou',
    category: 'decorative',
    icon: 'square',
    shortcuts: ['glass', 'verre'],
    defaultProps: {
      title: 'Effet verre',
      description: 'Carte avec fond flouté.',
      blur: 12,
      bgImage: '',
    },
  },
  typewriter: {
    type: 'typewriter',
    name: 'Texte tape-écran',
    description: 'Animation typewriter',
    category: 'decorative',
    icon: 'type',
    shortcuts: ['typewriter'],
    defaultProps: {
      texts: ['Bienvenue', 'Sur Docbel', 'Documents administratifs simplifiés'],
      speed: 80,
      loop: true,
      cursor: true,
    },
  },
  kenBurns: {
    type: 'kenBurns',
    name: 'Image Ken Burns',
    description: 'Image avec zoom lent',
    category: 'decorative',
    icon: 'image',
    shortcuts: ['kenburns', 'zoom'],
    defaultProps: { image: '', caption: '', duration: 20 },
  },
  particles: {
    type: 'particles',
    name: 'Particules',
    description: 'Fond animé de particules',
    category: 'decorative',
    icon: 'sparkles',
    shortcuts: ['particles'],
    defaultProps: { count: 40, color: '#C8102E', speed: 'normal' },
  },
  newsTicker: {
    type: 'newsTicker',
    name: 'Bandeau actu',
    description: 'Bandeau défilant d\'actualités',
    category: 'utility',
    icon: 'arrow-right',
    shortcuts: ['ticker', 'actu'],
    defaultProps: {
      items: [
        { label: 'Nouvelle réforme du chômage en 2026', date: '15 mars' },
        { label: 'Allocations familiales : changements dès janvier' },
        { label: 'CPAS : digitalisation des demandes' },
      ],
      speed: 'normal',
    },
  },

  // ═════════════════════ Education / a11y ═════════════════════
  flashcards: {
    type: 'flashcards',
    name: 'Flashcards',
    description: 'Cartes recto-verso',
    category: 'education',
    icon: 'graduation-cap',
    shortcuts: ['flashcards', 'cards'],
    defaultProps: {
      title: 'Apprenez les termes',
      items: [
        { front: 'CPAS', back: 'Centre Public d\'Action Sociale' },
        { front: 'IPP', back: 'Impôt des Personnes Physiques' },
        { front: 'BCE', back: 'Banque-Carrefour des Entreprises' },
      ],
    },
  },
  ttsButton: {
    type: 'ttsButton',
    name: 'Lire à voix haute',
    description: 'Synthèse vocale du contenu',
    category: 'education',
    icon: 'mic',
    shortcuts: ['tts', 'voix'],
    defaultProps: { label: 'Lire l\'article', voice: 'fr-FR' },
  },
  a11yToolbar: {
    type: 'a11yToolbar',
    name: 'Barre d\'accessibilité',
    description: 'Outils d\'accessibilité (taille texte, contraste)',
    category: 'education',
    icon: 'eye',
    shortcuts: ['a11y', 'accessibility'],
    defaultProps: {
      position: 'bottom-right',
      enableFontSizer: true,
      enableHighContrast: true,
      enableDyslexiaFont: true,
    },
  },
}

// Utility: pre-generate sample heatmap data for the past year
function generateSampleHeatmap() {
  const out: { date: string; value: number }[] = []
  const today = new Date()
  for (let i = 365; i >= 0; i--) {
    const d = new Date(today)
    d.setDate(d.getDate() - i)
    out.push({ date: d.toISOString().slice(0, 10), value: Math.floor(Math.random() * 5) })
  }
  return out
}

export function makeBlock<T extends BlockType>(type: T): Block<T> {
  const entry = BLOCK_REGISTRY[type]
  return {
    id: nanoid(),
    type,
    props: structuredClone(entry.defaultProps) as BlockPropsMap[T],
  } as Block<T>
}

export const BLOCKS_BY_CATEGORY: Record<BlockCategory, AnyBlockRegistryEntry[]> = (() => {
  const map: Record<BlockCategory, AnyBlockRegistryEntry[]> = {
    text: [],
    media: [],
    layout: [],
    marketing: [],
    ui: [],
    charts: [],
    engagement: [],
    navigation: [],
    editorial: [],
    docbel: [],
    utility: [],
    decorative: [],
    education: [],
  }
  for (const entry of Object.values(BLOCK_REGISTRY) as AnyBlockRegistryEntry[]) {
    map[entry.category].push(entry)
  }
  return map
})()
