/**
 * Convertit un libellé de pays FR (tel que stocké dans la table `nationalite`
 * de l'ONEM) en code ISO 3166-1 alpha-2. Le code ISO sert ensuite à afficher
 * un drapeau via la lib `flag-icons` (classes CSS `.fi.fi-{iso2}`, SVG natifs).
 *
 * Couvre les 459 entrées de la table `nationalite` :
 *  - noms de pays simples ("France" → FR)
 *  - variantes parenthétiques ("Allemagne (Rép.féd.)" → DE)
 *  - formes adjectivales "d'origine X" ("d'origine française" → FR)
 *  - territoires (Réunion, Guam, etc.) → drapeau du pays souverain
 *  - entités historiques (URSS, Yougoslavie, Tchécoslovaquie) → null (omis du map)
 *
 * Pourquoi côté code et pas DB ? Les codes BCSS/ONEM ne sont PAS des ISO codes
 * (101 = Albanie, ISO: AL). Le libellé FR est l'identifiant le plus stable au
 * fil des versions ONEM.
 */

const LABEL_TO_ISO2: Record<string, string> = {
  // ─── Europe ──────────────────────────────────────────────────────────
  albanie: 'AL',
  allemagne: 'DE',
  andorre: 'AD',
  arménie: 'AM',
  autriche: 'AT',
  azerbaïdjan: 'AZ',
  bélarus: 'BY',
  belgique: 'BE',
  'bosnie-herzégovine': 'BA',
  bulgarie: 'BG',
  chypre: 'CY',
  'cité du vatican': 'VA',
  croatie: 'HR',
  danemark: 'DK',
  espagne: 'ES',
  estonie: 'EE',
  'fédération de russie': 'RU',
  finlande: 'FI',
  france: 'FR',
  géorgie: 'GE',
  gibraltar: 'GI',
  grèce: 'GR',
  hongrie: 'HU',
  'iles canaries': 'ES',
  irlande: 'IE',
  islande: 'IS',
  italie: 'IT',
  kosovo: 'XK',
  lettonie: 'LV',
  liechtenstein: 'LI',
  lituanie: 'LT',
  luxembourg: 'LU',
  macédoine: 'MK',
  'macédoine du nord': 'MK',
  madère: 'PT',
  malte: 'MT',
  moldova: 'MD',
  moldavie: 'MD',
  monaco: 'MC',
  monténégro: 'ME',
  norvège: 'NO',
  'pays-bas': 'NL',
  pologne: 'PL',
  portugal: 'PT',
  'république tchèque': 'CZ',
  tchéquie: 'CZ',
  roumanie: 'RO',
  'royaume-uni': 'GB',
  russie: 'RU',
  'saint-marin': 'SM',
  'saint-siège': 'VA',
  serbie: 'RS',
  slovaquie: 'SK',
  slovénie: 'SI',
  suède: 'SE',
  suisse: 'CH',
  turquie: 'TR',
  ukraine: 'UA',
  vatican: 'VA',

  // ─── Asie ────────────────────────────────────────────────────────────
  'abu dhabi': 'AE',
  afghanistan: 'AF',
  'arabie saoudite': 'SA',
  bahreïn: 'BH',
  bangladesh: 'BD',
  bhoutan: 'BT',
  birmanie: 'MM',
  brunei: 'BN',
  'brunéi darussalam': 'BN',
  cambodge: 'KH',
  chine: 'CN',
  'corée du nord': 'KP',
  'corée du sud': 'KR',
  'emirats arabes unis': 'AE',
  'émirats arabes unis': 'AE',
  'hong-kong': 'HK',
  inde: 'IN',
  indonésie: 'ID',
  iran: 'IR',
  iraq: 'IQ',
  irak: 'IQ',
  israël: 'IL',
  japon: 'JP',
  jordanie: 'JO',
  kazakhstan: 'KZ',
  kirghizistan: 'KG',
  koweït: 'KW',
  laos: 'LA',
  liban: 'LB',
  macao: 'MO',
  malaisie: 'MY',
  maldives: 'MV',
  mongolie: 'MN',
  myanmar: 'MM',
  népal: 'NP',
  oman: 'OM',
  ouzbékistan: 'UZ',
  pakistan: 'PK',
  palestine: 'PS',
  philippines: 'PH',
  qatar: 'QA',
  'république khmer du cambogde': 'KH',
  'république socialiste du vietnam': 'VN',
  singapour: 'SG',
  'sri lanka': 'LK',
  syrie: 'SY',
  tadjikistan: 'TJ',
  taïwan: 'TW',
  'territoire palestinien': 'PS',
  thaïlande: 'TH',
  timor: 'TL',
  'timor-leste': 'TL',
  turkménistan: 'TM',
  vietnam: 'VN',
  yemen: 'YE',
  yémen: 'YE',

  // ─── Afrique ─────────────────────────────────────────────────────────
  'afars et issas': 'DJ',
  'afrique du sud': 'ZA',
  algérie: 'DZ',
  angola: 'AO',
  'archipel des comores': 'KM',
  bénin: 'BJ',
  botswana: 'BW',
  'burkina faso': 'BF',
  burundi: 'BI',
  cabinda: 'AO',
  cameroun: 'CM',
  'cap vert': 'CV',
  comores: 'KM',
  congo: 'CG',
  // Discriminateurs : "Congo (Rép. dém.)" = RDC, "Congo (République du)" = Brazzaville
  'congo rép dém': 'CD',
  'congo république démocratique': 'CD',
  'congo république du': 'CG',
  'congo-brazzaville': 'CG',
  "côte d'ivoire": 'CI',
  djibouti: 'DJ',
  egypte: 'EG',
  égypte: 'EG',
  erythrée: 'ER',
  érythrée: 'ER',
  ethiopie: 'ET',
  éthiopie: 'ET',
  'fernando poo': 'GQ',
  gabon: 'GA',
  gambie: 'GM',
  ghana: 'GH',
  guinée: 'GN',
  'guinée équatoriale': 'GQ',
  'guinée portugaise': 'GW',
  'guinée-bissau': 'GW',
  'haute-volta': 'BF',
  'ile de santhomé': 'ST',
  'iles du cap vert': 'CV',
  kenya: 'KE',
  lesotho: 'LS',
  libéria: 'LR',
  libye: 'LY',
  madagascar: 'MG',
  malawi: 'MW',
  mali: 'ML',
  maroc: 'MA',
  maurice: 'MU',
  mauritanie: 'MR',
  mozambique: 'MZ',
  namibie: 'NA',
  ngwane: 'SZ',
  niger: 'NE',
  nigéria: 'NG',
  ouganda: 'UG',
  'république centrafricaine': 'CF',
  'république de djibouti': 'DJ',
  réunion: 'RE',
  rwanda: 'RW',
  'sahara occidental': 'EH',
  'sainte-hélène': 'SH',
  'sao tomé et principe': 'ST',
  sénégal: 'SN',
  seychelles: 'SC',
  'sierra leone': 'SL',
  somalie: 'SO',
  soudan: 'SD',
  'soudan du sud': 'SS',
  swaziland: 'SZ',
  tanzanie: 'TZ',
  tchad: 'TD',
  togo: 'TG',
  tunisie: 'TN',
  urundi: 'BI',
  zaire: 'CD',
  zaïre: 'CD',
  zambie: 'ZM',
  zimbabwe: 'ZW',

  // ─── Amériques ───────────────────────────────────────────────────────
  anguilla: 'AI',
  antigua: 'AG',
  'antigua-et-barbuda': 'AG',
  'antilles françaises': 'FR',
  argentine: 'AR',
  bahamas: 'BS',
  barbade: 'BB',
  belize: 'BZ',
  bermudes: 'BM',
  bolivie: 'BO',
  brésil: 'BR',
  canada: 'CA',
  chili: 'CL',
  colombie: 'CO',
  'costa rica': 'CR',
  cuba: 'CU',
  dominique: 'DM',
  'el salvador': 'SV',
  equateur: 'EC',
  équateur: 'EC',
  "etats-unis d'amérique": 'US',
  'etats-unis': 'US',
  'états-unis': 'US',
  grenade: 'GD',
  guadeloupe: 'GP',
  guatemala: 'GT',
  guatémala: 'GT',
  guyana: 'GY',
  'guyane française': 'GF',
  'guyane hollandaise': 'SR',
  haïti: 'HT',
  honduras: 'HN',
  'honduras britannique': 'BZ',
  'ile de dominica': 'DM',
  'iles caïmanes': 'KY',
  'iles falkland': 'FK',
  'iles turks et caïques': 'TC',
  'iles vierges américaines': 'VI',
  'iles vierges britanniques': 'VG',
  jamaïque: 'JM',
  'kitts and nevis': 'KN',
  'le groenland': 'GL',
  martinique: 'MQ',
  mexique: 'MX',
  montserrat: 'MS',
  nicaragua: 'NI',
  panama: 'PA',
  paraguay: 'PY',
  pérou: 'PE',
  'porto-rico': 'PR',
  'république dominicaine': 'DO',
  'saint-barthélemy': 'BL',
  'saint-pierre-et-miquelon': 'PM',
  'saint-vincent-et-les-grenadines': 'VC',
  'sainte lucie': 'LC',
  'st. kitts et nevis': 'KN',
  surinam: 'SR',
  suriname: 'SR',
  'trinité-et-tobago': 'TT',
  uruguay: 'UY',
  venezuela: 'VE',

  // ─── Océanie ─────────────────────────────────────────────────────────
  'archipel des carolines': 'FM',
  australie: 'AU',
  cook: 'CK',
  fidji: 'FJ',
  guam: 'GU',
  hawaï: 'US',
  'iles cook': 'CK',
  'iles gilbert': 'KI',
  'iles marshall': 'MH',
  'iles salomon': 'SB',
  micronésie: 'FM',
  nauru: 'NR',
  niué: 'NU',
  'nouvelle-calédonie': 'NC',
  'nouvelle-zélande': 'NZ',
  'nouvelles - hebrides': 'VU',
  palau: 'PW',
  'papouasie-nouvelle-guinée': 'PG',
  pitcairn: 'PN',
  'polynésie française': 'PF',
  'samoa américaines': 'AS',
  'samoa occidentales': 'WS',
  tahiti: 'PF',
  "territ.dép.de l'australie": 'AU',
  'territ.dép.de la nelle zélande': 'NZ',
  tokelau: 'TK',
  tonga: 'TO',
  tuvalu: 'TV',
  vanuatu: 'VU',
  'wallis et futuna': 'WF',

  // ─── Statuts britanniques (codes 905-909) ────────────────────────────
  'citoyen britannique': 'GB',
  "citoyen britannique d'outre-mer": 'GB',
  'citoyen des t.o.m. britanniques': 'GB',
  'ressortissant britannique': 'GB',
  'sous la protection britannique': 'GB',
  'sujet britannique': 'GB',

  // ─── "d'origine X" — formes adjectivales (codes 744-902) ─────────────
  "d'origine afghane": 'AF',
  "d'origine albanaise": 'AL',
  "d'origine algérienne": 'DZ',
  "d'origine allemande": 'DE',
  "d'origine angolaise": 'AO',
  "d'origine arménienne": 'AM',
  "d'origine argentine": 'AR',
  "d'origine autrichienne": 'AT',
  "d'origine azerbaïdjanaise": 'AZ',
  "d'origine bahreïnie": 'BH',
  "d'origine bangladeshienne": 'BD',
  "d'origine béninoise": 'BJ',
  "d'origine bhoutanaise": 'BT',
  "d'origine biélorusse": 'BY',
  "d'origine birmane": 'MM',
  "d'origine bolivienne": 'BO',
  "d'origine bosniaque": 'BA',
  "d'origine brésilienne": 'BR',
  "d'origine bulgare": 'BG',
  "d'origine burundaise": 'BI',
  "d'origine cambodgienne": 'KH',
  "d'origine camerounaise": 'CM',
  "d'origine capverdienne": 'CV',
  "d'origine centrafricaine": 'CF',
  "d'origine chilienne": 'CL',
  "d'origine chinoise": 'CN',
  "d'origine colombienne": 'CO',
  "d'origine congolaise": 'CD',
  "d'origine congolaise brazzaville": 'CG',
  "d'origine coréenne": 'KR',
  "d'origine croate": 'HR',
  "d'origine cubaine": 'CU',
  "d'origine d'abu dhabi": 'AE',
  "d'origine d'afrique du sud": 'ZA',
  "d'origine de côte d'ivoire": 'CI',
  "d'origine de haute-volta": 'BF',
  "d'origine de serbie et monténégro": 'RS',
  "d'origine de sierra leone": 'SL',
  "d'origine djiboutienne": 'DJ',
  "d'origine dominicaine": 'DO',
  "d'origine du burkina faso": 'BF',
  "d'origine du sierra leone": 'SL',
  "d'origine égyptienne": 'EG',
  "d'origine équato-guinéenne": 'GQ',
  "d'origine équatorienne": 'EC',
  "d'origine érythréenne": 'ER',
  "d'origine espagnole": 'ES',
  "d'origine estonienne": 'EE',
  "d'origine éthiopienne": 'ET',
  "d'origine finlandaise": 'FI',
  "d'origine française": 'FR',
  "d'origine gabonaise": 'GA',
  "d'origine gambienne": 'GM',
  "d'origine géorgienne": 'GE',
  "d'origine ghanéenne": 'GH',
  "d'origine grecque": 'GR',
  "d'origine guatémaltèque": 'GT',
  "d'origine guinéenne": 'GN',
  "d'origine guyanaise": 'GY',
  "d'origine haïtienne": 'HT',
  "d'origine hondurienne": 'HN',
  "d'origine hongroise": 'HU',
  "d'origine indienne": 'IN',
  "d'origine indonésienne": 'ID',
  "d'origine iranienne": 'IR',
  "d'origine irakienne": 'IQ',
  "d'origine israëlienne": 'IL',
  "d'origine italienne": 'IT',
  "d'origine jamaïcaine": 'JM',
  "d'origine jordanienne": 'JO',
  "d'origine kazakh": 'KZ',
  "d'origine kenyane": 'KE',
  "d'origine khmer": 'KH',
  "d'origine kirghize": 'KG',
  "d'origine kosovare": 'XK',
  "d'origine koweïtienne": 'KW',
  "d'origine laotienne": 'LA',
  "d'origine lettone": 'LV',
  "d'origine libanaise": 'LB',
  "d'origine libérienne": 'LR',
  "d'origine libyenne": 'LY',
  "d'origine lithuanienne": 'LT',
  "d'origine macédonienne": 'MK',
  "d'origine malagassy": 'MG',
  "d'origine malaisienne": 'MY',
  "d'origine malienne": 'ML',
  "d'origine marocaine": 'MA',
  "d'origine mauricienne": 'MU',
  "d'origine mauritanienne": 'MR',
  "d'origine mexicaine": 'MX',
  "d'origine moldave": 'MD',
  "d'origine mongolienne": 'MN',
  "d'origine monténégrine": 'ME',
  "d'origine mozambique": 'MZ',
  "d'origine namibienne": 'NA',
  "d'origine népalaise": 'NP',
  "d'origine nicaraguayenne": 'NI',
  "d'origine nigériane": 'NG',
  "d'origine nigérienne": 'NE',
  "d'origine omanaise": 'OM',
  "d'origine ougandaise": 'UG',
  "d'origine ouzbeks": 'UZ',
  "d'origine pakistanaise": 'PK',
  "d'origine palestinienne": 'PS',
  "d'origine panaméenne": 'PA',
  "d'origine paraguayenne": 'PY',
  "d'origine péruvienne": 'PE',
  "d'origine philippines": 'PH',
  "d'origine polonaise": 'PL',
  "d'origine portugaise": 'PT',
  "d'origine qatarie": 'QA',
  "d'origine roumaine": 'RO',
  "d'origine russe": 'RU',
  "d'origine rwandaise": 'RW',
  "d'origine salvadorienne": 'SV',
  "d'origine santoméenne": 'ST',
  "d'origine saoudienne": 'SA',
  "d'origine sénégalaise": 'SN',
  "d'origine slovène": 'SI',
  "d'origine somalienne": 'SO',
  "d'origine soudanaise": 'SD',
  "d'origine srilankaise": 'LK',
  "d'origine sud-soudanaise": 'SS',
  "d'origine swazie": 'SZ',
  "d'origine syrienne": 'SY',
  "d'origine tadjike": 'TJ',
  "d'origine tanzanienne": 'TZ',
  "d'origine tchadienne": 'TD',
  "d'origine tchèque": 'CZ',
  "d'origine thaïlandaise": 'TH',
  "d'origine tibétaine": 'CN',
  "d'origine timoraise": 'TL',
  "d'origine togolaise": 'TG',
  "d'origine tunisienne": 'TN',
  "d'origine turkmène": 'TM',
  "d'origine turque": 'TR',
  "d'origine ukrainienne": 'UA',
  "d'origine uruguayenne": 'UY',
  "d'origine vénézuélienne": 'VE',
  "d'origine vietnamienne": 'VN',
  "d'origine yéménite": 'YE',
  "d'origine zaïroise": 'CD',
  "d'origine zambienne": 'ZM',
  "d'origine zimbabwéenne": 'ZW',
  "originaire de guinée-bissau": 'GW',
  "originaire de myanmar": 'MM',
  "originaire des emirats arabes unis": 'AE',
}

/**
 * Renvoie le code ISO 3166-1 alpha-2 correspondant à un libellé de nationalité
 * ONEM, ou `null` si on n'a pas de mapping fiable (apatride, entité historique
 * dissoute, libellé inconnu).
 *
 * Deux niveaux de lookup :
 *  1. Forme normalisée complète (parens transformées en espaces) — discrimine
 *     "Congo (Rép. dém.)" → CD vs "Congo (République du)" → CG.
 *  2. Tête du libellé (avant la première parenthèse / virgule) — couvre les
 *     entrées simples sans avoir à dupliquer chaque variante.
 */
export function getCountryIso2(label: string): string | null {
  if (!label) return null
  const lower = label.toLowerCase()

  // Forme complète : parens et ponctuation remplacées par des espaces.
  const full = lower
    .replace(/[(),.]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
  if (LABEL_TO_ISO2[full]) return LABEL_TO_ISO2[full]

  // Tête avant la première parenthèse ou virgule.
  const head = lower.split(/[(),]/)[0].trim()
  if (head && LABEL_TO_ISO2[head]) return LABEL_TO_ISO2[head]

  return null
}
