/** Résolution nom d'icône (string DB) → composant lucide, pour le module Formations. */
import {
  Award,
  BadgeCheck,
  BookOpen,
  Briefcase,
  Calculator,
  Clock,
  EyeOff,
  Euro,
  FileCheck,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  HardHat,
  HeartHandshake,
  Keyboard,
  Languages,
  Lock,
  MapPin,
  MonitorSmartphone,
  Rocket,
  Scale,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Truck,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  Award,
  BadgeCheck,
  BookOpen,
  Briefcase,
  Calculator,
  Clock,
  EyeOff,
  Euro,
  FileCheck,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  HardHat,
  HeartHandshake,
  Keyboard,
  Languages,
  Lock,
  MapPin,
  MonitorSmartphone,
  Rocket,
  Scale,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Truck,
  Users,
  Wrench,
};

export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (name && ICON_MAP[name]) return ICON_MAP[name];
  return GraduationCap;
}
